import AuthBackground from '@/components/auth/AuthBackground';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthFormContextProvider from '@/context/auth/AuthFormContext';
import ReactQueryContext from '@/context/common/ReactQueryContext';
import UserContextProvider from '@/context/auth/UserContext';
import { Suspense } from 'react';
import GlobalLoading from '@/components/common/loading/GlobalLoading/GlobalLoading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='kor'>
      <body className={inter.className}>
        <Suspense fallback={null}>
          <GlobalLoading />
        </Suspense>
        <ReactQueryContext>
          <UserContextProvider>
            <AuthFormContextProvider>
              {children}

              <AuthBackground />
            </AuthFormContextProvider>
          </UserContextProvider>
        </ReactQueryContext>
        <div id='portal'></div>
        <div id='review-portal'></div>
      </body>
    </html>
  );
}
