import AuthBackground from '@/components/auth/AuthBackground';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthContextProvider from '@/context/auth/AuthFormContext';
import AuthFormContextProvider from '@/context/auth/AuthFormContext';
import ReactQueryContext from '@/context/common/ReactQueryContext';
import UserContextProvider from '@/context/auth/UserContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='kr'>
      <body className={inter.className}>
        <ReactQueryContext>
          <UserContextProvider>
            <AuthFormContextProvider>
              {children}
              <AuthBackground />
            </AuthFormContextProvider>
          </UserContextProvider>
        </ReactQueryContext>
        <div id='portal'></div>
      </body>
    </html>
  );
}
